version: '3.8'
services:
  app:
    build: .
    ports:
      - "443:443"
    depends_on:
      - mysql
    networks:
      - ict-cloud-spring-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: wjdqhqhdks
      MYSQL_DATABASE: ICT_CLOUD
    ports:
      - "3306:3306"
    networks:
      - ict-cloud-spring-network

networks:
  ict-cloud-spring-network:
    driver: bridge
